version: '3'

volumes:
  db: {}

services:
  CurrencyRateAggregationService:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/
    ports:
      - 5432:5432

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dream
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432